Repository ladybug-tools/honeybee-radiance, pull requests merged in 2021-02, with the labels that each got.

#419 fix(deps): Remove [cli] option in favor of making it a requirement
  Dockerfile
  README.md
  cli-requirements.txt
  docs/index.rst
  honeybee_radiance/cli/__init__.py
  honeybee_radiance/cli/dc.py
  honeybee_radiance/cli/grid.py
  honeybee_radiance/cli/lib.py
  honeybee_radiance/cli/octree.py
  honeybee_radiance/cli/raytrace.py
  honeybee_radiance/cli/sky.py
  honeybee_radiance/cli/sunpath.py
  honeybee_radiance/cli/translate.py
  setup.py
Labels: enhancement

#424 docs(modifierset): Fix incorrect docstring
  honeybee_radiance/modifierset.py
Labels: documentation

#434 feat(cli): Add commands needed for thermal mapping
  honeybee_radiance/cli/edit.py
  honeybee_radiance/cli/translate.py
  honeybee_radiance/sensorgrid.py
  tests/assets/model/model_complete_multiroom_radiance.hbjson
  tests/assets/model/model_radiance_dynamic_states.hbjson
  tests/assets/model/two_rooms.hbjson
  tests/cli/edit_cli_test.py
  tests/cli/translate_cli_test.py
Labels: new development

#436 fix(cli): Forgot to add edit cli group to main
  honeybee_radiance/cli/__init__.py
  honeybee_radiance/cli/edit.py
Labels: bug

#443 fix(cli): Remove unnecessary keys from log file
  honeybee_radiance/cli/translate.py
Labels: bug

#447 fix(writer): keep the order for input sensors after filtering
  honeybee_radiance/writer.py
Labels: bug
