Repository ladybug-tools/honeybee-radiance, pull requests merged in 2023-02, with the labels that each got.

#803 fix(multiphase): Avoid octree creation if light path is filtered out
  honeybee_radiance/cli/multiphase.py
Labels: bug

#808 fix(room): Add new ways to generate sensor grids
  honeybee_radiance/cli/edit.py
  honeybee_radiance/cli/grid.py
  honeybee_radiance/geometry/polygon.py
  honeybee_radiance/properties/model.py
  honeybee_radiance/properties/room.py
  tests/model_extend_test.py
  tests/room_extend_test.py
Labels: new development

#809 docs(edit): Improve docstrings
  honeybee_radiance/cli/edit.py
  honeybee_radiance/cli/grid.py
  honeybee_radiance/properties/room.py
Labels: documentation

#810 fix(grid): Add option for --punched-geometry in exterior face grids
  README.md
  honeybee_radiance/cli/edit.py
  honeybee_radiance/cli/grid.py
  honeybee_radiance/properties/model.py
  honeybee_radiance/properties/room.py
Labels: enhancement

#811 fix(grid): Ensure SensorGrid identifiers are unique
  .github/workflows/ci.yaml
  honeybee_radiance/properties/room.py
Labels: bug
